_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: Demand_AUS_eval
  offset: 47332
  eval_length: 15777
  prediction_lengths: [1, 12, 24, 36, 48, 60, 72]
  context_lengths: [512]
  patch_sizes: [32, 64]