_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  - _target_: uni2ts.data.builder.simple.SimpleEvalDatasetBuilder
    dataset: Demand_eval
    offset: 36821
#    windows: 10
    windows: 12273
    distance: 1
    prediction_length: 1
    context_length: 512
    patch_size: 32
  - _target_: uni2ts.data.builder.simple.SimpleEvalDatasetBuilder
    dataset: Demand_eval
    offset: 36821
#    windows: 10
    windows: 12262
    distance: 1
    prediction_length: 12
    context_length: 512
    patch_size: 32
  - _target_: uni2ts.data.builder.simple.SimpleEvalDatasetBuilder
    dataset: Demand_eval
    offset: 36821
#    windows: 10
    windows: 12202
    distance: 1
    prediction_length: 72
    context_length: 512
    patch_size: 32