_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  - _target_: uni2ts.data.builder.simple.generate_eval_builders
    dataset: ???
    offset: ???
    eval_length: ???
    prediction_lengths: [1, 3, 7, 14, 30]
    context_lengths: [512]
    patch_sizes: [16, 32]