_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: Carbon_monthly_eval
  offset: 79
  eval_length: 26
  prediction_lengths:  [1, 2, 4, 6, 8, 10, 12, 14, 16, 18]
  context_lengths: [16, 18, 20]
  patch_sizes: [8]