_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: Carbon_daily_eval
  offset: 1641
  eval_length: 547
  prediction_lengths: [1, 2, 3, 4, 5, 7, 14, 21, 28, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 180, 365, 545]
  context_lengths: [512]
  patch_sizes: [32, 64]