_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: Demand_sg_daily_long_eval
  offset: 2221
  eval_length: 740
  prediction_lengths: [720]
  context_lengths: [1024, 1536]
  patch_sizes: [32, 64]